### ISSUE TITLE
Calibration process

### ISSUE THREAD

**Issue by GeoIH** [geda/hx711-lopy#5]
Hi 

Can you help me with the process for calibration and use for the script  scale.py
Im using hx711_spi.py on esp32 microcontroller.

thanks in advanced.

**Comment by amotl** [comment]
Dear @GeoIH,

we are using @geda's `hx711.py` (thanks a stack for conceiving this!) within the [Terkin Datalogger] framework, see [^1]. Following up on your question, we just added the guideline [HX711 scale adjustment with MicroPython] to our forum, where I would also like to invite you, hereby.

While the corresponding [ScaleAdjustment] code is based on [Terkin's SensorManager], I've outlined a path to a variant of this sketch to use with the lowlevel `hx711.py` driver within the post referenced above. If this can spark your interest, it would be sweet to see a corresponding patch submitted here, in order to give something back to the community of this original library. Do you see any chance to tackle this?

With kind regards,
Andreas.

[HX711 scale adjustment with MicroPython]: https://community.hiveeyes.org/t/hx711-scale-adjustment-with-micropython/4378
[ScaleAdjustment]: https://github.com/hiveeyes/terkin-datalogger/blob/0.13.0/src/lib/terkin/sensor/scale.py
[Terkin Datalogger]: https://github.com/hiveeyes/terkin-datalogger
[Terkin's SensorManager]: https://github.com/hiveeyes/terkin-datalogger/blob/0.13.0/src/lib/terkin/sensor/core.py#L23-L209
[^1]: https://community.hiveeyes.org/tag/terkin

**Comment by GeoIH** [comment]
Hi @amotl, thanks for your reply, but, how must connect the hx711 device and how libraries must upload (use) to the esp32 microcontroller, maybe a tutorial ??
thanks in advance.

**Comment by amotl** [comment]
Dear @GeoIH,

sorry that I can't help here, I am not a hardware guy at all. There are many resources on the net about how to wire the HX711, and for MicroPython on ESP32 as well.

With kind regards,
Andreas.

**Comment by GeoIH** [comment]
Thanks @amotl anyway.

Well, if someone need helps for make a scale script. I used the hx711.py library on the esp32. and I have to do these steps.
1. conecctions are like you want for clock_pin and data_pin. and creates the object (eg. hx=HX711(clock_pin, data_pin))
2. use the method set_scale() for put the scale to zero.
3. put over the scale a known weigth depending of scale used (eg. if the scale is max 1kg, put a known weight aprox like 990 gr.)  and use the method get_units() for obtain a value.
4. the value gets of get_units() divide by the known weight.
5. the value from step 4, put in the set_scale() method (eg. set_scale(2323,203))
6.  now you can use get_units() method for gets the weight of any object (obviously in range of the scale).

Note: if the value of weight varies a little bit, you can change the value of set_scale(xxxxx) moving the value + or -. 
The SPI library, I  couldn't used it, it takes a time obtein the value. I don't know what happenned.
